FROM python:3.9-slim

WORKDIR /app

# Copiar el archivo requirements.txt en el contenedor
COPY ./Insano-Tube/requirements.txt .

# Instalar las dependencias
RUN apt-get update && \
    apt-get install -y ffmpeg wget && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    python3 -m pip install -r requirements.txt && \
    python3 -m pip install --upgrade yt-dlp

# Copiar el resto del código en el contenedor
COPY ./Insano-Tube/ .

CMD ["python3", "main.py"]
